sudo: false
language: python
python:
        - "2.7"
cache:
        directories:
                - $HOME/gcloud/

env:
        - GCLOUD=$HOME/gcloud/google-cloud-sdk/bin CLOUDSDK_PYTHON_SITEPACKAGES=1 GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/credentials.json

before_install:
        - openssl aes-256-cbc -K $encrypted_cf36da7dba4f_key -iv $encrypted_cf36da7dba4f_iv -in client_secret.json.enc -out client_secret.json -d

script:
        - python test.py