sudo: false
language: python
python:
        - "2.7"
cache:
        directories:
                - $HOME/gcloud/

env:
        - GCLOUD=$HOME/gcloud/google-cloud-sdk/bin CLOUDSDK_PYTHON_SITEPACKAGES=1 GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/credentials.json


before_install:
        #secrets
        openssl aes-256-cbc -K $encrypted_9a4798c88375_key -iv $encrypted_9a4798c88375_iv -in secrets.tar.enc -out secrets.tar -d

script:
        - python test.py