sudo: false
language: python
python:
        - "2.7"
cache:
        directories:
                - $HOME/gcloud/
                - $HOME/.pip-cache

env:
        - GCLOUD=$HOME/gcloud/google-cloud-sdk/bin

before_install:
        #Install gcloud
        - if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
                mkdir -p $HOME/gcloud &&
                wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud &&
                cd $HOME/gcloud &&
                tar xzf google-cloud-sdk.tar.gz &&
                printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh &&
                cd $TRAVIS_BUILD_DIR;
          fi

        # Auth
        - openssl aes-256-cbc -K $encrypted_cf36da7dba4f_key -iv $encrypted_cf36da7dba4f_iv -in hello-webapp2.json.enc -out hello-webapp2.json -d
install:
        - pip install tox --download-cache $HOME/.pip-cache

script:
        - cd python/
        - tox
